### ISSUE TITLE
updating data with reset_view = True doesn't update the behavior of the Reset view button

### ISSUE THREAD

**Issue by abast** [flekschas/jupyter-scatter#160]
Step 1: Create scatter plot with random data

```
import jscatter
import numpy as np
import pandas as pd

data1 = pd.DataFrame({
    "x": np.random.rand(1000),
    "y": np.random.rand(1000),
})
data2 = pd.DataFrame({
    "x": 2*np.random.rand(1000),
    "y": 2*np.random.rand(1000),
})
s0 = jscatter.Scatter(data=data1, x="x", y="y", width=500, height=500)
s0.show()
```

Step 2: update the dataset. 
`s0.data(data=data2, animate = True, reset_view = True) 
`
Step 3: click the Reset view button. This resets the view to the original dataset ranges (data1), not the updated ranges.

**Comment by flekschas** [comment]
This is expected because `data2` is plotted in the space of `data1` and the reset button resets the camera to the original data space. The `reset_view` argument of `scatter.data()` is essentially just zooming to the data extent of the new data.

At an essence, if you want to treat the new data as the reference frame, call `scatter.data(..., reset_scales=True)`. Then the reset view button will behave as expected.

However, I realize that the wording and docstring are confusing. Maybe `reset_view` should be called `zoom_view`. I've added a PR to fix the confusion: https://github.com/flekschas/jupyter-scatter/pull/162. Let me know what you think.

**Comment by abast** [comment]
Thanks, I think the new naming is much clearer. Honestly, I read reset_view and didn't even look at the docstring because I felt so sure about what that keyword argument must be doing.

**Comment by flekschas** [comment]
> I read reset_view and didn't even look at the docstring because I felt so sure about what that keyword argument must be doing.

100% agreed! Thanks for bringing this up. The renaming/refactor is going out with the next version.
